version: "3"

services:
  
  # hello-world-nginx
  hello-nginx: 
    build: ../hello-world-nginx
#    networks:
#      - hellodevops-net
    ports:
      - "3000:3000"
      - "3002:3002"
    restart: always
#    volumes:
#      - ./templates:/etc/nginx/templates


  # hello-world-node application
  hello-node:
    build: ../hello-world-nodejs
    volumes: 
      - ../hello-world-nodejs:/opt/hello-world-nodejs
#    networks:
#      - hellodevops-net
#    ports:
#      - "9443:9443"
    depends_on:
      - hello-nginx
    restart: on-failure


  # hello-world-golang application
  hello-golang:
    build: ../hello-world-golang
    volumes: 
      - ../hello-world-golang:/opt/hello-world-golang
#    networks:
#      - hellodevops-net
    depends_on:
      - hello-nginx
    restart: on-failure
#    ports:
#      - "8080:8080"


#networks:
# hellodevops-net:
#    driver: bridge
