version: "3.8"

services:
  
# hello-world-nginx
  hello-nginx:
    container_name: nginx-container
    build: ./hello-world-nginx
    networks:
      - bootcamp-net
    ports:
      - "80:18181"
    restart: always
    volumes:
      - ./hello-world-nginx/docker-depends:/etc/nginx/conf.d


# hello-world-node application
  hello-node:
    container_name: nodejs-container
    build: ./hello-world-nodejs
    volumes: 
      - ./hello-world-nodejs:/usr/app
    networks:
      - bootcamp-net
    ports:
      - "3000:3000"
    depends_on:
      - hello-nginx
    restart: on-failure


# hello-world-golang application
  hello-golang:
    container_name: golang-container
    build: ./hello-world-golang
    volumes: 
      - ./hello-world-golang:/go/src/app
    networks:
      - bootcamp-net
    depends_on:
      - hello-nginx
    restart: on-failure
    ports:
      - "3002:3002"


networks:
 bootcamp-net:
    driver: bridge
