version: "3"

services:
  
  # hello-world-nginx
  hello-nginx: 
    build: ../hello-world-nginx
#    networks:
#      - hellodevops-net
#    ports:
#      - "3306:3306"
#    command: --default-authentication-plugin=mysql_native_password
    restart: always
#    volumes:
#      - .:/docker-entrypoint-initdb.d
#    environment: 
#      MYSQL_ROOT_PASSWORD: password


  # hello-world-node application
  hello-node:
    build: ../hello-world-nodejs
#    volumes: 
#      - ../hello-node:/opt/hello-node
#    networks:
#      - hellodevops-net
#    ports:
#      - "9443:9443"
    depends_on:
      - hello-nginx
    restart: on-failure
#    environment:
#      RABBITMQ_HOST: mq
#      MYSQL_HOST: db
#      MYSQL_PASSWORD: password


  # hello-world-golang application
  hello-golang:
    build: ../hello-world-golang
#    volumes: 
#      - ../hello-python:/opt/hello-python
#    networks:
#      - hellodevops-net
    depends_on:
      - hello-nginx
    restar: on-failure
#    ports:
#      - "8080:8080"
#    environment:
#      RABBITMQ_HOST: mq



#networks:
# hellodevops-net:
#    driver: bridge
