name: Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
    REGISTRY: margus23
    IMAGE_NAME_GO: image-golang
    IMAGE_NAME_NODE: image-node


jobs:
  build-docker-go:
    runs-on: ubuntu-latest
    needs: build-go
    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: ./hello-world-golang
        push: true
        tags: ${{ env.REGISTRY }}/${{ ENV.IMAGE_NAME_GO }}:latest


  build-docker-node:
    runs-on: ubuntu-latest
    needs: build-node
    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: ./hello-world-nodejs
        push: true
        tags: ${{ env.REGISTRY }}/${{ ENV.IMAGE_NAME_NODE }}:latest